# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 813950a431869d9ea1b62a699a75cb554e43aa8150eecb03f2f0f67ed3a26028c343df8a946ec198837f0ed2d323bdefeb08fcab9d81674eeeb8c61a9697b09d

test:
  secret_key_base: b3637eb1c8fdc1cb02c0bd6b341ed3490ea6eed43b83654600428dc5bb8662de5960dbe8815b54af1fd3f41031d5a506c660477b6077dde71220ddbe7f8381e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
